### Register
POST http://localhost:8080/api/users
Accept: application/json
Content-Type: application/json

{
  "username": "razzaq",
  "password": "rahasia",
  "name": "Abdul Razzaq",
  "email": "test@mail.com"
}

### Login
POST http://localhost:8080/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "razzaq",
  "password": "rahasia"
}

### Token
POST http://localhost:8080/api/auth/token
Accept: application/json
Content-Type: application/json

{
  "token": "037f8697-2f21-40d2-a7e4-e1c08c185524"
}

### Get User
GET http://localhost:8080/api/users/current
Accept: application/json
X-API-TOKEN: 553ebf8d-2d20-4489-960b-9756995c9002

### Update User
PATCH http://localhost:8080/api/users/current
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 5834aaaf-1e01-474a-a119-7326848714c1

{
  "name": "Abdul Razzaq Baru"
}

### Logout User
DELETE http://localhost:8080/api/auth/logout
Accept: application/json
X-API-TOKEN: 553ebf8d-2d20-4489-960b-9756995c9002